# make it explicit that we favor the new container-based travis workers
sudo: false

language: python

cache:
  apt: true
  # We use three different cache directory
  # to work around a Travis bug with multi-platform cache
  directories:
  - $HOME/.cache/pip
  - $HOME/download
env:
  global:
    # Directory where tests are run from
    - TEST_DIR=/tmp/test_dir/
    - MODULE=skrules
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="2.7" COVERAGE="true"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.17.0" CYTHON_VERSION="0.23.5"
      PANDAS_VERSION="0.18.1"

    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"
      NUMPY_VERSION="1.10.4" SCIPY_VERSION="0.17.0" CYTHON_VERSION="0.23.5"
      PANDAS_VERSION="0.18.1"

    # This environment tests the newest supported Anaconda release (4.4.0)
    # It also runs tests requiring Pandas.
    - DISTRIB="conda" PYTHON_VERSION="3.6.1" INSTALL_MKL="true"
      NUMPY_VERSION="1.13" SCIPY_VERSION="0.19.0" PANDAS_VERSION="0.20.2"
      CYTHON_VERSION="0.25.2" COVERAGE=true

    # This environment use pytest to run the tests. It uses the newest
    # supported Anaconda release (4.4.0). It also runs tests requiring Pandas.
    - USE_PYTEST="true" DISTRIB="conda" PYTHON_VERSION="3.6.1"
      INSTALL_MKL="true" NUMPY_VERSION="1.12.1" SCIPY_VERSION="0.19.0"
      PANDAS_VERSION="0.20.1" CYTHON_VERSION="0.25.2"
      TEST_DOCSTRINGS="true"

    # flake8 linting on diff wrt common ancestor with upstream/master
    - RUN_FLAKE8="true" SKIP_TESTS="true"
      DISTRIB="conda" PYTHON_VERSION="3.5" INSTALL_MKL="true"
      NUMPY_VERSION="1.13" SCIPY_VERSION="0.19.0" CYTHON_VERSION="0.23.5"


install: source ci_scripts/travis/install.sh
script: bash ci_scripts/travis/test.sh
after_success: source ci_scripts/travis/success.sh
